### ISSUE TITLE
Extension not working for some users

### ISSUE THREAD

**Issue by PaulVS-Qlik** [stefanwalther/sense-media-box#10] opened 2017-06-01 19:49 UTC
Hello Stefan,

I have developed a couple of apps using the latest version but when i share the app, the extension does not work properly.  

The results show a blank screen.  We have tested/troubleshooted from many angles and cannot seem to get it to work on other people's machines.

Any ideas?

thanks,

PVS

**Comment by PaulVS-Qlik** [comment] 2017-06-02 12:40
I believe this might be a Windows 10 issue.  that is the single difference that i can identify across my laptop v. others that are helping me.

**Comment by stefanwalther** [comment] 2017-06-29 12:52
Can you share the app. Based on what you are saying it's really hard to start investigating. What do those users only seeing a blank screen seen in the Chrome Dev-Tool's console? Is there anything you can share?

**Comment by chrislarsenqlik** [comment] 2017-07-14 20:07
I'm experiencing the same issue. Josefine Stal is also seeing the same thing. When we use an iframe as the html source it first only shows a blank screen. We enter Edit mode and we can see the content. If we change the size of the object on the canvas (slightly wider or higher) it becomes blank in Edit mode, but then when clicking Done it shows up as desired when not in edit mode! I'm happy to share the QVF via email if you'd like.

**Comment by stefanwalther** [comment] 2017-08-18 18:06
Should be fixed with version v0.4.2 of sense-media-box.
Closing this issue, please feel free to re-open if the problem is not fixed.

**Closed by stefanwalther** 2017-08-18 18:06 UTC
Labels: type:bug
