### ISSUE TITLE
Not working in sense 2.2.3

### ISSUE THREAD

**Issue by Shivshankarsharma** [stefanwalther/sense-media-box#3] opened 2016-04-10 12:47 UTC
kindly suggest how to make it work. Its not working in Qlik sense 2.2.3 for image display or anything else.

I can see extension, pulled it too and put a path too like below -

'https://.../DBAlmarai.jpg'

I have tried this also -
'https://C:\Users\shiv.s\Documents\Qlik\Sense\Content\Default\DBAlmarai.jpg'

This picture is placed at 

C:\Users\shiv.s\Documents\Qlik\Sense\Content\Default\DBAlmarai.jpg

**Comment by stefanwalther** [comment] 2016-05-19 22:02
Using local files is by design not recommended and therefore currently not supported.
But if you have uploaded something to the content folder (static content), then try to use the following path, which works, just double-checked:

`/media/9b35407e05748d072b704f69ccfd5235/Qlik_default_flower.png`

so in your case probably

'/DBAimarai.jpg`

That's it ...

**Comment by stefanwalther** [comment] 2016-05-20 18:56
Closing, since it is not a bug, but works as designed.

**Closed by stefanwalther** 2016-05-20 18:56 UTC
Labels: question
